model = "gpt-5"
approval_policy = "on-request"
# profile = "gpt-5"

##########################################
# Profiles
##########################################
[profiles.gpt-5]
model = "gpt-5"
model_provider = "openai"
model_verbosity = "medium"
approval_policy = "on-request"

#######################################################
##################       Network      #################
#######################################################
[sandobox_read_only]
network_access = true

[sandobox_workspace_write]
network_access = true

[features]
web_search_request = true

# [mcp_servers.serena]
# command = "uvx"
# args = [
#     "--from",
#     "git+https://github.com/oraios/serena",
#     "serena",
#     "start-mcp-server",
#     "--context",
#     "codex",
# ]
# startup_timeout_ms = 20_000

# [mcp_servers.context7]
# command = "npx"
# args = ["-y", "@upstash/context7-mcp"]
#
# [mcp_servers.sequential-thinking]
# command = "npx"
# args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.time]
command = "uvx"
args = ["mcp-server-time"]

[mcp_servers.git]
command = "uvx"
args = ["mcp-server-git"]

# [mcp_servers.tavily]
# command = "npx"
# args = ["-y", "tavily-mcp@latest"]
# startup_timeout_ms = 20_000
